### ISSUE TITLE
Implement convenient trace function

### ISSUE THREAD

**Issue by felixSchl** [garyb/purescript-debug#1]
Could we not, for sake of convenience, do:

``` purescript
trace' :: forall a m. (Show a, Monad m) => a -> m Unit
trace' = traceShow x \_ -> pure unit
```

...or something similar.  This avoids typing it out manually al the time. One could argue the function should be called `traceShow'`.

**Comment by garyb** [comment]
I've never used it like that actually (I'd just use `traceShow x \_ -> some action in m`) but I don't see the harm in adding some variations of that form. I'd suggest we have `traceA` / `traceShowA` / `traceAnyA` though, and use an `Applicative` constraint rather than `Monad`, as you only need the `pure`.

**Comment by felixSchl** [comment]
Yeah, agreed. I can hand in an accompanying pull request later today.
